// Shared seed rows for the `properties` table, used by both the standalone
// seed script (seed-properties.ts) and the startup auto-ensure (ensure-properties.ts).
// ensureProperties() only INSERTS missing rows (ON CONFLICT DO NOTHING); it never
// deletes, so removing a row here does not remove it from the live DB — delete that
// separately (Admin → Stays, or the properties.delete API).

export const PROPERTY_SEED_ROWS = [
  {
    name: 'Irish Pirate',
    slug: 'irish-pirate',
    host: 'Blue Skies Partner',
    location: 'Key Colony Beach',
    type: 'Waterfront Home',
    guests: 10,
    bedrooms: 3,
    bathrooms: 2,
    rating: null,
    reviews: 0,
    description:
      'Newly renovated canal-front home in Key Colony Beach with a private heated pool, dockage, and quick ocean access. Sleeps the whole crew across three bedrooms — including a kids’ bunk room — with a bright open living space, a chef’s kitchen with a marble island, spa-style walk-in showers, and a covered grilling patio steps from the water. Pair it with a boat day and you’re on the water in minutes.',
    highlights: JSON.stringify([
      'Private heated pool',
      'Canal-front with dock',
      'Quick ocean access',
      'Renovated chef’s kitchen',
      'Spa walk-in showers',
      'Kids’ bunk room',
      'Covered grilling patio',
      'Sleeps the whole crew',
    ]),
    pricePerNight: 0, // set in Admin → Stays
    cleaningFee: 175,
    imageUrl: '/homes/irish-pirate-aerial.jpg',
    galleryImages: JSON.stringify([
      '/homes/irish-pirate-aerial.jpg',
      '/homes/irish-pirate-pool.jpg',
      '/homes/irish-pirate-living-1.jpg',
      '/homes/irish-pirate-living-2.jpg',
      '/homes/irish-pirate-kitchen-1.jpg',
      '/homes/irish-pirate-kitchen-2.jpg',
      '/homes/irish-pirate-bedroom-1.jpg',
      '/homes/irish-pirate-bedroom-2.jpg',
      '/homes/irish-pirate-bunk-1.jpg',
      '/homes/irish-pirate-bunk-2.jpg',
      '/homes/irish-pirate-bath-1.jpg',
      '/homes/irish-pirate-bath-2.jpg',
      '/homes/irish-pirate-bath-3.jpg',
      '/homes/irish-pirate-bath-4.jpg',
      '/homes/irish-pirate-grill.jpg',
    ]),
    status: 'active' as const,
    sortOrder: 0,
  },
  {
    name: 'Tarpon Landing',
    slug: 'tarpon-landing',
    host: 'Blue Skies Partner',
    location: 'Key Colony Beach',
    type: 'Waterfront Home',
    guests: 8,
    bedrooms: 2,
    bathrooms: 2,
    rating: null,
    reviews: 0,
    description:
      'Bright single-story canal-front home in Key Colony Beach with a private dock, boat lift, and a palm-shaded waterfront patio. The open kitchen and living areas with granite counters look out over the water, and two comfortable bedrooms make it an easy waterfront escape. Step off the dock and you are minutes from the flats, the reef, and open water.',
    highlights: JSON.stringify([
      'Canal-front with dock & boat lift',
      'Waterfront patio',
      'Open kitchen & living',
      'Two bedrooms',
      'Walk-in shower',
      'In-unit laundry',
      'Steps to the water',
      'Minutes to the reef',
    ]),
    pricePerNight: 0, // set in Admin → Stays
    cleaningFee: 175,
    imageUrl: '/homes/key-colony-aerial.jpg',
    galleryImages: JSON.stringify([
      '/homes/key-colony-aerial.jpg',
      '/homes/key-colony-exterior-front.jpg',
      '/homes/key-colony-living-1.jpg',
      '/homes/key-colony-living-2.jpg',
      '/homes/key-colony-dining.jpg',
      '/homes/key-colony-kitchen.jpg',
      '/homes/key-colony-bedroom-1.jpg',
      '/homes/key-colony-bedroom-2.jpg',
      '/homes/key-colony-bedroom-3.jpg',
      '/homes/key-colony-bedroom-4.jpg',
      '/homes/key-colony-bath-1.jpg',
      '/homes/key-colony-laundry.jpg',
      '/homes/key-colony-backyard-1.jpg',
      '/homes/key-colony-backyard-2.jpg',
    ]),
    status: 'active' as const,
    sortOrder: 5,
  },
  {
    name: 'Conch Cottage',
    slug: 'conch-cottage',
    host: 'Blue Skies Partner',
    location: 'Key Colony Beach',
    type: 'Waterfront Home',
    guests: 8,
    bedrooms: 2,
    bathrooms: 2,
    rating: null,
    reviews: 0,
    description:
      'Classic Keys canal-front home on 3rd Street in Key Colony Beach, with warm wood-beamed ceilings, an open kitchen and living area, and sliders that open to a waterfront patio with dock and dining. Two bedrooms, including a bunk room for the kids, and fresh walk-in showers make it easy for the whole group. Tie up at the dock and you are minutes from the flats, the reef, and open water.',
    highlights: JSON.stringify([
      'Canal-front with dock',
      'Waterfront patio & dining',
      'Wood-beamed ceilings',
      'Open kitchen & living',
      'Bunk room for kids',
      'Walk-in showers',
      'Steps to the water',
      'Minutes to the reef',
    ]),
    pricePerNight: 0, // set in Admin → Stays
    cleaningFee: 175,
    imageUrl: '/homes/key-colony-2-backyard-2.jpg',
    galleryImages: JSON.stringify([
      '/homes/key-colony-2-backyard-2.jpg',
      '/homes/key-colony-2-exterior-front.jpg',
      '/homes/key-colony-2-patio.jpg',
      '/homes/key-colony-2-living.jpg',
      '/homes/key-colony-2-kitchen-1.jpg',
      '/homes/key-colony-2-kitchen-2.jpg',
      '/homes/key-colony-2-bedroom-1.jpg',
      '/homes/key-colony-2-bedroom-2.jpg',
      '/homes/key-colony-2-bunk.jpg',
      '/homes/key-colony-2-bath-1.jpg',
      '/homes/key-colony-2-bath-2.jpg',
      '/homes/key-colony-2-bath-3.jpg',
      '/homes/key-colony-2-bath-4.jpg',
      '/homes/key-colony-2-backyard-1.jpg',
    ]),
    status: 'active' as const,
    sortOrder: 7,
  },
];
